field: 350c29f3-6541-46c0-9209-dae7e78f1029 # hero contents
fieldLayouts:
  6a5d535e-fa66-4367-8046-26dc1197b27a:
    tabs:
      -
        elements:
          -
            fieldUid: a94c04c3-f89b-4f11-be33-1079598f82d9 # discription
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a94c04c3-f89b-4f11-be33-1079598f82d9: # discription
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: discription
    instructions: ''
    name: discription
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: heroDiscription
name: 'hero discription'
sortOrder: 3
