field: 350c29f3-6541-46c0-9209-dae7e78f1029 # hero contents
fieldLayouts:
  6695a729-5b7a-4365-83a5-adea57cbc150:
    tabs:
      -
        elements:
          -
            fieldUid: b49659a5-9b47-44e0-8826-17357114ca1b # icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b49659a5-9b47-44e0-8826-17357114ca1b: # icons
    contentColumnType: string
    fieldGroup: null
    handle: icons
    instructions: ''
    name: icons
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5b42acb9-1fcc-4ac0-8f9b-859724eba742' # Image Discription
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5b42acb9-1fcc-4ac0-8f9b-859724eba742' # Image Discription
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5b42acb9-1fcc-4ac0-8f9b-859724eba742' # Image Discription
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: heroIcons
name: 'hero icons'
sortOrder: 4
