field: 350c29f3-6541-46c0-9209-dae7e78f1029 # hero contents
fieldLayouts:
  667b4d8b-1c51-4a4a-996f-232d2ab7d254:
    tabs:
      -
        elements:
          -
            fieldUid: d4482a4b-2aff-4f26-bec0-ad44c555d7c2 # link name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b6678be-30e6-4351-a092-8a9cd57025bf # link url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8aab4f9d-41d7-434d-a509-c1e2dcfefb84 # button class
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b6678be-30e6-4351-a092-8a9cd57025bf: # link url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'link url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  8aab4f9d-41d7-434d-a509-c1e2dcfefb84: # button class
    columnSuffix: mojlfqah
    contentColumnType: text
    fieldGroup: null
    handle: buttonClass
    instructions: ''
    name: 'button class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d4482a4b-2aff-4f26-bec0-ad44c555d7c2: # link name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkName
    instructions: ''
    name: 'link name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heroLinks
name: 'hero links'
sortOrder: 5
