field: 09853f07-331b-4464-900b-17c70dcbad5d # Hero Section Matrix
fieldLayouts:
  4a8b11ed-8d64-4fbe-b1db-5fc07aeb007b:
    tabs:
      -
        elements:
          -
            fieldUid: 7c45023e-873a-42ac-b026-ab45a253fd81 # Hero Discription
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 500b6cf6-4e37-44c5-92b7-968c52d5c131 # Hero Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cef29595-df5e-43be-b779-9ec5e160dbba # hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7c45023e-873a-42ac-b026-ab45a253fd81: # Hero Discription
    contentColumnType: text
    fieldGroup: null
    handle: herodiscription
    instructions: ''
    name: 'Hero Discription'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  500b6cf6-4e37-44c5-92b7-968c52d5c131: # Hero Heading
    contentColumnType: text
    fieldGroup: null
    handle: heroHeading
    instructions: ''
    name: 'Hero Heading'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cef29595-df5e-43be-b779-9ec5e160dbba: # hero Image
    contentColumnType: string
    fieldGroup: null
    handle: heroImage
    instructions: ''
    name: 'hero Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5b42acb9-1fcc-4ac0-8f9b-859724eba742' # Image Discription
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5b42acb9-1fcc-4ac0-8f9b-859724eba742' # Image Discription
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5b42acb9-1fcc-4ac0-8f9b-859724eba742' # Image Discription
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: heroSection
name: 'Hero Section'
sortOrder: 1
