field: b84ff370-f477-4eb6-a805-c07b76e72ea8 # nav links
fieldLayouts:
  70cbc60c-5484-443c-b4de-a08cf11837cb:
    tabs:
      -
        elements:
          -
            fieldUid: bac8d5ff-4ad6-4d62-909b-eaf4416b178b # link name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ffa21403-9d6f-412a-a599-b674ffb8e2e1 # link url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  bac8d5ff-4ad6-4d62-909b-eaf4416b178b: # link name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkName
    instructions: ''
    name: 'link name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ffa21403-9d6f-412a-a599-b674ffb8e2e1: # link url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'link url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: navRow3
name: 'nav Row 3'
sortOrder: 3
