contentColumnType: text
fieldGroup: bd18aa1f-a7a3-4f6a-badc-d60a2f389e77 # about
handle: aboutUsHeading
instructions: ''
name: 'About Us Heading'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
