contentColumnType: string
fieldGroup: 53ac96b1-ba2b-47b7-abd9-ca965844d512 # Common
handle: heroSectionMatrix
instructions: ''
name: 'Hero Section Matrix'
searchable: true
settings:
  contentTable: '{{%matrixcontent_herosectionmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
