columnSuffix: null
contentColumnType: string
fieldGroup: e9af3e97-4e9a-46de-a82f-8ffcc655e997 # hero
handle: heroContents
instructions: ''
name: 'hero contents'
searchable: true
settings:
  contentTable: '{{%matrixcontent_herocontents}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
