contentColumnType: string
fieldGroup: dd13b668-050e-4b90-b743-b164aeb1d68c # Navlinks
handle: navLinks2
instructions: ''
name: 'Nav Links 2'
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:38665262-19b0-444a-be54-43f393887140' # Nav Links 2
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
