contentColumnType: string(255)
fieldGroup: dd13b668-050e-4b90-b743-b164aeb1d68c # Navlinks
handle: navLink1
instructions: ''
name: 'Nav Link 1'
searchable: true
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
