contentColumnType: string(255)
fieldGroup: 53ac96b1-ba2b-47b7-abd9-ca965844d512 # Common
handle: socialLink
instructions: ''
name: 'Social Link'
searchable: true
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
