fieldLayouts:
  fd97061f-193a-466b-80bb-dbe11df80c22:
    tabs:
      -
        elements:
          -
            fieldUid: f1221d17-7f54-4435-b173-f6bbaa63f091 # Footer Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53edf543-fc53-482a-bc03-27298c2e40e6 # Footer Disclaimer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fa989d5a-8e1d-4698-8ba4-8038eeae3311 # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: b84ff370-f477-4eb6-a805-c07b76e72ea8 # nav links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: links
        sortOrder: 2
handle: footer
name: Footer
sortOrder: 1
