defaultPlacement: end
enableVersioning: true
handle: dummy2
name: dummy2
propagationMethod: all
siteSettings:
  d5f1d19a-569c-4bd6-9599-42df2dce89f8: # new craft
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: dummy2
type: single
