defaultPlacement: end
enableVersioning: true
handle: shop
name: Shop
propagationMethod: all
siteSettings:
  d5f1d19a-569c-4bd6-9599-42df2dce89f8: # new craft
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: shop
type: single
